import AppKit
import Foundation

final class ClipboardMonitor {
    private static let transientMarkerType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let concealedMarkerType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let autoGeneratedMarkerType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private let pasteboard: NSPasteboard
    private let representationStore: ClipboardRepresentationStore
    private let sourceApplicationProvider: () -> ClipboardSourceApplication?
    private var timer: Timer?
    private var lastChangeCount: Int
    private var onNewItem: ((ClipboardItem) -> Void)?
    private var wakeObserver: NSObjectProtocol?
    private let processingQueue = DispatchQueue(label: "edison.clipboard.processing", qos: .utility)

    init(
        pasteboard: NSPasteboard = .general,
        representationStore: ClipboardRepresentationStore = .shared,
        sourceApplicationProvider: (() -> ClipboardSourceApplication?)? = nil
    ) {
        self.pasteboard = pasteboard
        self.representationStore = representationStore
        self.sourceApplicationProvider = sourceApplicationProvider ?? {
            guard let application = NSWorkspace.shared.frontmostApplication,
                  let bundleIdentifier = application.bundleIdentifier else {
                return nil
            }

            return ClipboardSourceApplication(
                bundleIdentifier: bundleIdentifier,
                localizedName: application.localizedName
            )
        }
        self.lastChangeCount = pasteboard.changeCount
    }

    func start(onNewItem: @escaping (ClipboardItem) -> Void) {
        self.onNewItem = onNewItem
        timer?.invalidate()
        registerWakeObserverIfNeeded()

        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            self?.pollPasteboard()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        if let wakeObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(wakeObserver)
            self.wakeObserver = nil
        }
    }

    func markCurrentChangeObserved() {
        lastChangeCount = pasteboard.changeCount
    }

    private func pollPasteboard() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        processPasteboardSnapshot(expectedChangeCount: changeCount)
    }

    private func registerWakeObserverIfNeeded() {
        guard wakeObserver == nil else { return }
        wakeObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didWakeNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            self?.handleWake()
        }
    }

    private func handleWake() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        processPasteboardSnapshot(expectedChangeCount: changeCount)
    }

    private func processPasteboardSnapshot(expectedChangeCount: Int) {
        let pasteboard = self.pasteboard
        let sourceApplication = sourceApplicationProvider()
        processingQueue.async { [weak self] in
            guard let item = self?.makeClipboardItem(
                from: pasteboard,
                expectedChangeCount: expectedChangeCount,
                sourceApplication: sourceApplication
            ) else { return }
            DispatchQueue.main.async {
                self?.onNewItem?(item)
            }
        }
    }

    private func makeClipboardItem(
        from pasteboard: NSPasteboard,
        expectedChangeCount: Int,
        sourceApplication: ClipboardSourceApplication?
    ) -> ClipboardItem? {
        guard pasteboard.changeCount == expectedChangeCount,
              !shouldSkipStorage(for: pasteboard.types),
              let pasteboardItem = pasteboard.pasteboardItems?.first else {
            return nil
        }

        if let text = pasteboardItem.string(forType: .string), !text.isEmpty {
            let itemID = UUID()
            let richTypes: Set<NSPasteboard.PasteboardType> = [.rtf, .rtfd, .html]
            let allowlistedTypes: Set<NSPasteboard.PasteboardType> = [.string, .rtf, .rtfd, .html]
            let declaredTypes = pasteboardItem.types.filter { allowlistedTypes.contains($0) }
            let hasRichRepresentation = declaredTypes.contains { richTypes.contains($0) }

            guard hasRichRepresentation else {
                guard pasteboard.changeCount == expectedChangeCount else { return nil }
                return ClipboardItem(
                    id: itemID,
                    sourceApplication: sourceApplication,
                    payload: .text(text)
                )
            }

            let readableRepresentations = declaredTypes.compactMap { type -> (String, Data)? in
                guard let data = pasteboardItem.data(forType: type) else { return nil }
                return (type.rawValue, data)
            }
            let readableTypes = Set(readableRepresentations.map(\.0))
            let saved = representationStore.save(
                representations: readableRepresentations,
                declaredTypeIdentifiers: declaredTypes.map(\.rawValue),
                itemID: itemID
            )
            let unreadable = declaredTypes.compactMap { type -> ClipboardRepresentationDegradation? in
                guard !readableTypes.contains(type.rawValue) else { return nil }
                return ClipboardRepresentationDegradation(typeIdentifier: type.rawValue, reason: .readFailure)
            }
            let textRepresentations = ClipboardTextRepresentations(
                declaredTypeIdentifiers: saved.declaredTypeIdentifiers,
                storedRepresentations: saved.storedRepresentations,
                degradations: saved.degradations + unreadable
            )
            let item = ClipboardItem(
                id: itemID,
                sourceApplication: sourceApplication,
                payload: .text(text),
                textRepresentations: textRepresentations
            )

            guard pasteboard.changeCount == expectedChangeCount else {
                representationStore.delete(item.textRepresentations)
                return nil
            }
            return item
        }

        if let tiffData = pasteboardItem.data(forType: .tiff),
           let prepared = ImageProcessing.prepareImagePayload(from: tiffData) {
            guard pasteboard.changeCount == expectedChangeCount else {
                ImageStore.delete(relativePath: prepared.imagePath)
                ImageStore.delete(relativePath: prepared.thumbnailPath)
                return nil
            }
            return ClipboardItem(
                sourceApplication: sourceApplication,
                payload: .image(prepared)
            )
        }

        if let fileURL = pasteboard.readObjects(forClasses: [NSURL.self], options: nil)?.first as? URL {
            guard pasteboard.changeCount == expectedChangeCount else { return nil }
            return ClipboardItem(
                sourceApplication: sourceApplication,
                payload: .fileURL(fileURL)
            )
        }

        if let value = pasteboardItem.string(forType: .fileURL),
           let url = URL(string: value) {
            guard pasteboard.changeCount == expectedChangeCount else { return nil }
            return ClipboardItem(
                sourceApplication: sourceApplication,
                payload: .fileURL(url)
            )
        }

        return nil
    }

    func shouldSkipStorage(for types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types else { return false }

        return types.contains(Self.transientMarkerType)
            || types.contains(Self.concealedMarkerType)
            || types.contains(Self.autoGeneratedMarkerType)
    }
}
