import AppKit
import Foundation

final class ClipboardMonitor {
    private static let transientMarkerType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let concealedMarkerType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let autoGeneratedMarkerType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private let pasteboard: NSPasteboard
    private let sourceApplicationProvider: () -> ClipboardSourceApplication?
    private var timer: Timer?
    private var lastChangeCount: Int
    private var onNewItem: ((ClipboardItem) -> Void)?
    private var wakeObserver: NSObjectProtocol?
    private let processingQueue = DispatchQueue(label: "edison.clipboard.processing", qos: .utility)

    init(
        pasteboard: NSPasteboard = .general,
        sourceApplicationProvider: (() -> ClipboardSourceApplication?)? = nil
    ) {
        self.pasteboard = pasteboard
        self.sourceApplicationProvider = sourceApplicationProvider ?? {
            guard let application = NSWorkspace.shared.frontmostApplication,
                  let bundleIdentifier = application.bundleIdentifier else {
                return nil
            }

            return ClipboardSourceApplication(
                bundleIdentifier: bundleIdentifier,
                localizedName: application.localizedName
            )
        }
        self.lastChangeCount = pasteboard.changeCount
    }

    func start(onNewItem: @escaping (ClipboardItem) -> Void) {
        self.onNewItem = onNewItem
        timer?.invalidate()
        registerWakeObserverIfNeeded()

        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            self?.pollPasteboard()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        if let wakeObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(wakeObserver)
            self.wakeObserver = nil
        }
    }

    private func pollPasteboard() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        processPasteboardSnapshot()
    }

    private func registerWakeObserverIfNeeded() {
        guard wakeObserver == nil else { return }
        wakeObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didWakeNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            self?.handleWake()
        }
    }

    private func handleWake() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        processPasteboardSnapshot()
    }

    private func processPasteboardSnapshot() {
        let pasteboard = self.pasteboard
        let sourceApplication = sourceApplicationProvider()
        processingQueue.async { [weak self] in
            guard let item = self?.makeClipboardItem(from: pasteboard, sourceApplication: sourceApplication) else { return }
            DispatchQueue.main.async {
                self?.onNewItem?(item)
            }
        }
    }

    private func makeClipboardItem(
        from pasteboard: NSPasteboard,
        sourceApplication: ClipboardSourceApplication?
    ) -> ClipboardItem? {
        if shouldSkipStorage(for: pasteboard.types) {
            return nil
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            return ClipboardItem(
                sourceApplication: sourceApplication,
                payload: .text(text)
            )
        }

        if let tiffData = pasteboard.data(forType: .tiff),
           let prepared = ImageProcessing.prepareImagePayload(from: tiffData) {
            return ClipboardItem(
                sourceApplication: sourceApplication,
                payload: .image(prepared)
            )
        }

        if let fileURL = pasteboard.readObjects(forClasses: [NSURL.self], options: nil)?.first as? URL {
            return ClipboardItem(
                sourceApplication: sourceApplication,
                payload: .fileURL(fileURL)
            )
        }

        if let value = pasteboard.string(forType: .fileURL),
           let url = URL(string: value) {
            return ClipboardItem(
                sourceApplication: sourceApplication,
                payload: .fileURL(url)
            )
        }

        return nil
    }

    func shouldSkipStorage(for types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types else { return false }

        return types.contains(Self.transientMarkerType)
            || types.contains(Self.concealedMarkerType)
            || types.contains(Self.autoGeneratedMarkerType)
    }
}
