import AppKit
import Foundation

final class ClipboardMonitor {
    private static let transientMarkerType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let concealedMarkerType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let autoGeneratedMarkerType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int
    private var onNewItem: ((ClipboardItem) -> Void)?
    private let processingQueue = DispatchQueue(label: "edison.clipboard.processing", qos: .utility)

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    func start(onNewItem: @escaping (ClipboardItem) -> Void) {
        self.onNewItem = onNewItem
        timer?.invalidate()

        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            self?.pollPasteboard()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func pollPasteboard() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let pasteboard = self.pasteboard
        processingQueue.async { [weak self] in
            guard let item = self?.makeClipboardItem(from: pasteboard) else { return }
            DispatchQueue.main.async {
                self?.onNewItem?(item)
            }
        }
    }

    private func makeClipboardItem(from pasteboard: NSPasteboard) -> ClipboardItem? {
        if shouldSkipStorage(for: pasteboard.types) {
            return nil
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            return ClipboardItem(payload: .text(text))
        }

        if let tiffData = pasteboard.data(forType: .tiff),
           let prepared = ImageProcessing.prepareImagePayload(from: tiffData) {
            return ClipboardItem(payload: .image(prepared))
        }

        if let value = pasteboard.string(forType: .fileURL),
           let url = URL(string: value) {
            return ClipboardItem(payload: .fileURL(url))
        }

        return nil
    }

    func shouldSkipStorage(for types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types else { return false }

        return types.contains(Self.transientMarkerType)
            || types.contains(Self.concealedMarkerType)
            || types.contains(Self.autoGeneratedMarkerType)
    }
}
